/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as RaporYazRouteImport } from './routes/rapor-yaz'
import { Route as RevizyonRouteImport } from './routes/revizyon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporYazRoute = RaporYazRouteImport.update({
  id: '/rapor-yaz',
  path: '/rapor-yaz',
  getParentRoute: () => rootRouteImport,
} as any)
const RevizyonRoute = RevizyonRouteImport.update({
  id: '/revizyon',
  path: '/revizyon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/rapor-yaz': typeof RaporYazRoute
  '/revizyon': typeof RevizyonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/rapor-yaz': typeof RaporYazRoute
  '/revizyon': typeof RevizyonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/rapor-yaz': typeof RaporYazRoute
  '/revizyon': typeof RevizyonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ayarlar' | '/rapor-yaz' | '/revizyon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ayarlar' | '/rapor-yaz' | '/revizyon'
  id: '__root__' | '/' | '/ayarlar' | '/rapor-yaz' | '/revizyon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  RaporYazRoute: typeof RaporYazRoute
  RevizyonRoute: typeof RevizyonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapor-yaz': {
      id: '/rapor-yaz'
      path: '/rapor-yaz'
      fullPath: '/rapor-yaz'
      preLoaderRoute: typeof RaporYazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revizyon': {
      id: '/revizyon'
      path: '/revizyon'
      fullPath: '/revizyon'
      preLoaderRoute: typeof RevizyonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  RaporYazRoute: RaporYazRoute,
  RevizyonRoute: RevizyonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
